services:
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - media_volume:/opt/app/web/media
    ports:
     - 80:80
    depends_on:
     - web
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - media_volume:/opt/app/web/media
    command: gunicorn cloudtalents.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.app
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data:
  media_volume:

